// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: TFT

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_MainContainer;
extern lv_obj_t * ui_MenuContainer;
extern lv_obj_t * ui_CookTempLabel;
extern lv_obj_t * ui_OnOffLabel;
extern lv_obj_t * ui_Spacer;
extern lv_obj_t * ui_WifiLabel;
extern lv_obj_t * ui_ProbeRow1Container;
extern lv_obj_t * ui_Probe1Container;
extern lv_obj_t * ui_Probe1Label;
extern lv_obj_t * ui_Temp1Label;
extern lv_obj_t * ui_Spacer2;
extern lv_obj_t * ui_Probe2Container;
extern lv_obj_t * ui_Probe2Label;
extern lv_obj_t * ui_Temp2Label;
extern lv_obj_t * ui_ProbeRow2Container;
extern lv_obj_t * ui_Probe3Container;
extern lv_obj_t * ui_Probe3Label;
extern lv_obj_t * ui_Temp3Label;
extern lv_obj_t * ui_Spacer3;
extern lv_obj_t * ui_Probe4Container;
extern lv_obj_t * ui_Probe4Label;
extern lv_obj_t * ui_Temp4Label;
extern lv_obj_t * ui_TempContainer;
extern lv_obj_t * ui_CookTimeLabel;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_CookTimeHoursLabel;
extern lv_obj_t * ui_CookTimeSeperatorLabel;
extern lv_obj_t * ui_CookTimeMinutesLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

