// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: TFT

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_MainContainer = NULL;
lv_obj_t * ui_MenuContainer = NULL;
lv_obj_t * ui_CookTempLabel = NULL;
lv_obj_t * ui_OnOffLabel = NULL;
lv_obj_t * ui_Spacer = NULL;
lv_obj_t * ui_WifiLabel = NULL;
lv_obj_t * ui_ProbeRow1Container = NULL;
lv_obj_t * ui_Probe1Container = NULL;
lv_obj_t * ui_Probe1Label = NULL;
lv_obj_t * ui_Temp1Label = NULL;
lv_obj_t * ui_Spacer2 = NULL;
lv_obj_t * ui_Probe2Container = NULL;
lv_obj_t * ui_Probe2Label = NULL;
lv_obj_t * ui_Temp2Label = NULL;
lv_obj_t * ui_ProbeRow2Container = NULL;
lv_obj_t * ui_Probe3Container = NULL;
lv_obj_t * ui_Probe3Label = NULL;
lv_obj_t * ui_Temp3Label = NULL;
lv_obj_t * ui_Spacer3 = NULL;
lv_obj_t * ui_Probe4Container = NULL;
lv_obj_t * ui_Probe4Label = NULL;
lv_obj_t * ui_Temp4Label = NULL;
lv_obj_t * ui_TempContainer = NULL;
lv_obj_t * ui_CookTimeLabel = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_CookTimeHoursLabel = NULL;
lv_obj_t * ui_CookTimeSeperatorLabel = NULL;
lv_obj_t * ui_CookTimeMinutesLabel = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Screen1, &ui_font_Solid_Wifi, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_MainContainer);
    lv_obj_set_width(ui_MainContainer, lv_pct(100));
    lv_obj_set_height(ui_MainContainer, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_MainContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MainContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_MainContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_MainContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MainContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MainContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MainContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_MainContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_MainContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuContainer = lv_obj_create(ui_MainContainer);
    lv_obj_remove_style_all(ui_MenuContainer);
    lv_obj_set_width(ui_MenuContainer, lv_pct(100));
    lv_obj_set_height(ui_MenuContainer, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_MenuContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MenuContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MenuContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_MenuContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_MenuContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CookTempLabel = lv_label_create(ui_MenuContainer);
    lv_obj_set_width(ui_CookTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CookTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CookTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CookTempLabel, "---°");
    ui_object_set_themeable_style_property(ui_CookTempLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_Text);
    ui_object_set_themeable_style_property(ui_CookTempLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_Text);
    lv_obj_set_style_text_font(ui_CookTempLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CookTempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CookTempLabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CookTempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CookTempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffLabel = lv_label_create(ui_MenuContainer);
    lv_obj_set_width(ui_OnOffLabel, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_OnOffLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnOffLabel, -30);
    lv_obj_set_y(ui_OnOffLabel, 2);
    lv_obj_set_align(ui_OnOffLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffLabel, "");
    ui_object_set_themeable_style_property(ui_OnOffLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_Text);
    ui_object_set_themeable_style_property(ui_OnOffLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_Text);

    ui_Spacer = lv_label_create(ui_MenuContainer);
    lv_obj_set_height(ui_Spacer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Spacer, 1);
    lv_obj_set_align(ui_Spacer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Spacer, "");

    ui_WifiLabel = lv_label_create(ui_MenuContainer);
    lv_obj_set_width(ui_WifiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiLabel, -2);
    lv_obj_set_y(ui_WifiLabel, 2);
    lv_obj_set_align(ui_WifiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiLabel, "");
    ui_object_set_themeable_style_property(ui_WifiLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Light_Text);
    ui_object_set_themeable_style_property(ui_WifiLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Light_Text);
    lv_obj_set_style_pad_left(ui_WifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProbeRow1Container = lv_obj_create(ui_MainContainer);
    lv_obj_remove_style_all(ui_ProbeRow1Container);
    lv_obj_set_width(ui_ProbeRow1Container, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ProbeRow1Container, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ProbeRow1Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ProbeRow1Container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ProbeRow1Container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ProbeRow1Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ProbeRow1Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ProbeRow1Container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Probe1Container = lv_obj_create(ui_ProbeRow1Container);
    lv_obj_remove_style_all(ui_Probe1Container);
    lv_obj_set_width(ui_Probe1Container, 57);
    lv_obj_set_height(ui_Probe1Container, LV_SIZE_CONTENT);    /// 74
    lv_obj_set_x(ui_Probe1Container, -5);
    lv_obj_set_y(ui_Probe1Container, 50);
    lv_obj_set_align(ui_Probe1Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Probe1Container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Probe1Container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Probe1Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Probe1Container, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Probe1Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Probe1Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Primary);
    lv_obj_set_style_bg_image_recolor(ui_Probe1Container, lv_color_hex(0xB0FF40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Probe1Container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Probe1Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Probe1Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Probe1Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Probe1Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Probe1Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Light_Text);
    ui_object_set_themeable_style_property(ui_Probe1Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Light_Text);

    ui_Probe1Label = lv_label_create(ui_Probe1Container);
    lv_obj_set_width(ui_Probe1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Probe1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Probe1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Probe1Label, "Probe 1");
    lv_obj_set_style_text_font(ui_Probe1Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp1Label = lv_label_create(ui_Probe1Container);
    lv_obj_set_width(ui_Temp1Label, lv_pct(100));
    lv_obj_set_height(ui_Temp1Label, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Temp1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp1Label, "74°");
    lv_obj_set_style_text_align(ui_Temp1Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp1Label, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spacer2 = lv_label_create(ui_ProbeRow1Container);
    lv_obj_set_width(ui_Spacer2, 2);
    lv_obj_set_height(ui_Spacer2, lv_pct(100));
    lv_obj_set_align(ui_Spacer2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Spacer2, "");

    ui_Probe2Container = lv_obj_create(ui_ProbeRow1Container);
    lv_obj_remove_style_all(ui_Probe2Container);
    lv_obj_set_width(ui_Probe2Container, 57);
    lv_obj_set_height(ui_Probe2Container, LV_SIZE_CONTENT);    /// 74
    lv_obj_set_x(ui_Probe2Container, -5);
    lv_obj_set_y(ui_Probe2Container, 50);
    lv_obj_set_align(ui_Probe2Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Probe2Container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Probe2Container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Probe2Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Probe2Container, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Probe2Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Probe2Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Primary);
    lv_obj_set_style_pad_left(ui_Probe2Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Probe2Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Probe2Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Probe2Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Probe2Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Light_Text);
    ui_object_set_themeable_style_property(ui_Probe2Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Light_Text);

    ui_Probe2Label = lv_label_create(ui_Probe2Container);
    lv_obj_set_width(ui_Probe2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Probe2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Probe2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Probe2Label, "Probe 2");
    lv_obj_set_style_text_font(ui_Probe2Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp2Label = lv_label_create(ui_Probe2Container);
    lv_obj_set_width(ui_Temp2Label, lv_pct(100));
    lv_obj_set_height(ui_Temp2Label, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Temp2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp2Label, "999°");
    lv_obj_set_style_text_align(ui_Temp2Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp2Label, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProbeRow2Container = lv_obj_create(ui_MainContainer);
    lv_obj_remove_style_all(ui_ProbeRow2Container);
    lv_obj_set_width(ui_ProbeRow2Container, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ProbeRow2Container, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ProbeRow2Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ProbeRow2Container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ProbeRow2Container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ProbeRow2Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ProbeRow2Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ProbeRow2Container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Probe3Container = lv_obj_create(ui_ProbeRow2Container);
    lv_obj_remove_style_all(ui_Probe3Container);
    lv_obj_set_width(ui_Probe3Container, 57);
    lv_obj_set_height(ui_Probe3Container, LV_SIZE_CONTENT);    /// 74
    lv_obj_set_x(ui_Probe3Container, -5);
    lv_obj_set_y(ui_Probe3Container, 50);
    lv_obj_set_align(ui_Probe3Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Probe3Container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Probe3Container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Probe3Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Probe3Container, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Probe3Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Probe3Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Primary);
    lv_obj_set_style_pad_left(ui_Probe3Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Probe3Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Probe3Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Probe3Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Probe3Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Light_Text);
    ui_object_set_themeable_style_property(ui_Probe3Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Light_Text);

    ui_Probe3Label = lv_label_create(ui_Probe3Container);
    lv_obj_set_width(ui_Probe3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Probe3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Probe3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Probe3Label, "Probe 3");
    lv_obj_set_style_text_font(ui_Probe3Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp3Label = lv_label_create(ui_Probe3Container);
    lv_obj_set_width(ui_Temp3Label, lv_pct(100));
    lv_obj_set_height(ui_Temp3Label, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Temp3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp3Label, "999°");
    lv_obj_set_style_text_align(ui_Temp3Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp3Label, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spacer3 = lv_label_create(ui_ProbeRow2Container);
    lv_obj_set_width(ui_Spacer3, 2);
    lv_obj_set_height(ui_Spacer3, lv_pct(100));
    lv_obj_set_align(ui_Spacer3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Spacer3, "");

    ui_Probe4Container = lv_obj_create(ui_ProbeRow2Container);
    lv_obj_remove_style_all(ui_Probe4Container);
    lv_obj_set_width(ui_Probe4Container, 57);
    lv_obj_set_height(ui_Probe4Container, LV_SIZE_CONTENT);    /// 74
    lv_obj_set_x(ui_Probe4Container, -5);
    lv_obj_set_y(ui_Probe4Container, 50);
    lv_obj_set_align(ui_Probe4Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Probe4Container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Probe4Container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Probe4Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Probe4Container, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Probe4Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Primary);
    ui_object_set_themeable_style_property(ui_Probe4Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Primary);
    lv_obj_set_style_pad_left(ui_Probe4Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Probe4Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Probe4Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Probe4Container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Probe4Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Light_Text);
    ui_object_set_themeable_style_property(ui_Probe4Container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Light_Text);

    ui_Probe4Label = lv_label_create(ui_Probe4Container);
    lv_obj_set_width(ui_Probe4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Probe4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Probe4Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Probe4Label, "Probe 4");
    lv_obj_set_style_text_font(ui_Probe4Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp4Label = lv_label_create(ui_Probe4Container);
    lv_obj_set_width(ui_Temp4Label, lv_pct(100));
    lv_obj_set_height(ui_Temp4Label, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Temp4Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp4Label, "999°");
    lv_obj_set_style_text_align(ui_Temp4Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp4Label, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempContainer = lv_obj_create(ui_MainContainer);
    lv_obj_remove_style_all(ui_TempContainer);
    lv_obj_set_width(ui_TempContainer, lv_pct(100));
    lv_obj_set_height(ui_TempContainer, LV_SIZE_CONTENT);    /// 74
    lv_obj_set_x(ui_TempContainer, -5);
    lv_obj_set_y(ui_TempContainer, 50);
    lv_obj_set_align(ui_TempContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TempContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TempContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TempContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_TempContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TempContainer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_Text);
    ui_object_set_themeable_style_property(ui_TempContainer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_Text);

    ui_CookTimeLabel = lv_label_create(ui_TempContainer);
    lv_obj_set_width(ui_CookTimeLabel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_CookTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CookTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CookTimeLabel, "Cook Timer");
    lv_obj_set_style_text_font(ui_CookTimeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_TempContainer);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Dark_Text);
    ui_object_set_themeable_style_property(ui_Container1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Dark_Text);
    lv_obj_set_style_text_font(ui_Container1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CookTimeHoursLabel = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_CookTimeHoursLabel, 28);
    lv_obj_set_height(ui_CookTimeHoursLabel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_CookTimeHoursLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CookTimeHoursLabel, "--");
    lv_obj_set_style_text_align(ui_CookTimeHoursLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CookTimeSeperatorLabel = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_CookTimeSeperatorLabel, 10);
    lv_obj_set_height(ui_CookTimeSeperatorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CookTimeSeperatorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CookTimeSeperatorLabel, ":");
    lv_obj_set_style_text_align(ui_CookTimeSeperatorLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CookTimeSeperatorLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CookTimeSeperatorLabel, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CookTimeSeperatorLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CookTimeSeperatorLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CookTimeMinutesLabel = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_CookTimeMinutesLabel, 28);
    lv_obj_set_height(ui_CookTimeMinutesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CookTimeMinutesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CookTimeMinutesLabel, "--");
    lv_obj_set_style_text_align(ui_CookTimeMinutesLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_MainContainer = NULL;
    ui_MenuContainer = NULL;
    ui_CookTempLabel = NULL;
    ui_OnOffLabel = NULL;
    ui_Spacer = NULL;
    ui_WifiLabel = NULL;
    ui_ProbeRow1Container = NULL;
    ui_Probe1Container = NULL;
    ui_Probe1Label = NULL;
    ui_Temp1Label = NULL;
    ui_Spacer2 = NULL;
    ui_Probe2Container = NULL;
    ui_Probe2Label = NULL;
    ui_Temp2Label = NULL;
    ui_ProbeRow2Container = NULL;
    ui_Probe3Container = NULL;
    ui_Probe3Label = NULL;
    ui_Temp3Label = NULL;
    ui_Spacer3 = NULL;
    ui_Probe4Container = NULL;
    ui_Probe4Label = NULL;
    ui_Temp4Label = NULL;
    ui_TempContainer = NULL;
    ui_CookTimeLabel = NULL;
    ui_Container1 = NULL;
    ui_CookTimeHoursLabel = NULL;
    ui_CookTimeSeperatorLabel = NULL;
    ui_CookTimeMinutesLabel = NULL;

}
