// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: TFT

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Primary[2] = {0xFF3D00, 0xFF3D00};
const ui_theme_variable_t _ui_theme_alpha_Primary[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Light_Text[2] = {0xE0E0E0, 0xE0E0E0};
const ui_theme_variable_t _ui_theme_alpha_Light_Text[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Dark_Text[2] = {0x171717, 0x171717};
const ui_theme_variable_t _ui_theme_alpha_Dark_Text[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DARK_ORANGE;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

